# Generated by Django 3.1 on 2020-08-25 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mydocs/', verbose_name='Document')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_copy', models.FileField(blank=True, null=True, upload_to='')),
                ('form_input_done', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('last_modified_by_id', models.CharField(blank=True, max_length=256, null=True)),
                ('last_modified_by_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('autofill_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=256, null=True)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, max_length=256, null=True)),
                ('cgst', models.FloatField(blank=True, null=True)),
                ('sgst', models.FloatField(blank=True, null=True)),
                ('igst', models.FloatField(blank=True, null=True)),
                ('total_taxable_amount', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('imei', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_address', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('additional_data', models.CharField(blank=True, default='', max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='mydocs')),
            ],
        ),
        migrations.CreateModel(
            name='TagCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.CharField(max_length=256)),
                ('annotation_type', models.CharField(blank=True, choices=[('image', 'image'), ('text', 'text')], default='image', max_length=20, null=True)),
                ('hmin', models.FloatField()),
                ('wmin', models.FloatField()),
                ('hmax', models.FloatField()),
                ('wmax', models.FloatField()),
                ('is_done', models.BooleanField(blank=True, default=False, null=True)),
                ('page_id', models.PositiveIntegerField()),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.document')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_Tag', to='invoice.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.FloatField()),
                ('item_rate', models.FloatField()),
                ('item_description', models.CharField(max_length=256)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='invoice.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
    ]
