# Generated by Django 3.1 on 2020-08-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.CharField(default='admin', max_length=256),
            preserve_default=False,
        ),
    ]
