# Generated by Django 3.1 on 2020-08-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
