# Generated by Django 3.1 on 2020-08-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_copy',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
