# Generated by Django 3.1 on 2020-08-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_document_image_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image_copy',
        ),
    ]
