# Generated by Django 3.1 on 2020-08-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf_copy',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='invoice.invoice'),
        ),
    ]
