# Generated by Django 3.1 on 2020-08-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_document_image_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cgst',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_taxable_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
