# Generated by Django 3.1 on 2020-08-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20200805_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('hmin', models.FloatField()),
                ('wmin', models.FloatField()),
                ('hmax', models.FloatField()),
                ('wmax', models.FloatField()),
                ('page_id', models.PositiveIntegerField()),
            ],
        ),
    ]
