# Generated by Django 3.1 on 2020-08-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_tagcoordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_q', models.FloatField()),
                ('item_r', models.FloatField()),
                ('item_d', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='tagcoordinate',
            old_name='label',
            new_name='annotation',
        ),
    ]
