# Generated by Django 3.1 on 2020-08-13 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20200812_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.document'),
        ),
    ]
