# Generated by Django 3.1 on 2020-08-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mydocs/', verbose_name='Document')),
            ],
        ),
        migrations.CreateModel(
            name='UploadPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='mydocs')),
            ],
        ),
    ]
