# Generated by Django 3.1 on 2020-08-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20200817_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='last_modified_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
