# Generated by Django 3.1 on 2020-08-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20200819_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cgst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gstin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='igst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sgst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_taxable_amount',
            field=models.FloatField(),
        ),
    ]
