# Generated by Django 3.1 on 2020-08-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20200819_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='autofill_done',
            field=models.BooleanField(default=False),
        ),
    ]
